### ISSUE TITLE
python save with specific fileformat

### ISSUE THREAD

**Issue by ClaGause** [zhinst/labone-api-examples#2]
Hello,

I'm having problems with saving the data from the MFIA via python. I want to save it in a specific directory and under a specific name and fileformat, here .csv as an example. There is a bunch of other code so I'm trying to show you only the relevant parts. 

sweeper = self.daq.sweep()
self.sweeper.set('save/directory', 'directory')
sweeper.set('save/save', 1) 
sweeper.set('save/filename', 'name')
sweeper.set('fileformat', 1)
result = sweeper.read()

I get the following error: Error during sweep execution: Path fileformat not found.

I would really appriciate your help! Thank you!

**Comment by ghost** [comment]
From what I see the problem seems to be that you specify the wrong path specifier for the `fileformat`

The path is `/save/fileformat` (see https://docs.zhinst.com/labone_api_user_manual/modules/sweeper/index.html#node_save_fileformat) but you used `fileformat`

so probably changing `sweeper.set('fileformat', 1)` to `sweeper.set('save/fileformat', 1)` should fix the problem

**Comment by ghost** [comment]
Also, from what I can see, you initiate the save `sweeper.set('save/save', 1)` before setting the filename and format. Not sure if that is intended or by accident. You should call `sweeper.set('save/save', 1)` after you have set all the save specific parameters.

Random side note: Instead of using `sweeper.set('fileformat', 1)` you can also use `sweeper.set('fileformat', 'csv')` as the node is of an enumerated integer.

**Comment by ClaGause** [comment]
Thank you! I changed it accordingly but it still doesn't seem to work. I'm specifing the path with sweeper.set('save/directory', 'path') when setting the filename, could that somehow be problematic? Or maybe it's the placement? I've placed it like this: 
```
sweeper.set('save/directory', 'path') 
sweeper.set('save/filename', measurement['saveas_var'])
sweeper.set('save/fileformat', measurement['fileformat_var'])
start_time = time.time()
sweeper.execute()
sweeper.set('endless', 1)
while (time.time() - self.start_time) < (measurement['duration_var'] * measurement['durationunit_var']):
         time.sleep(0.05)
sweeper.set('endless', 0)
sweeper.set('save/save', 1)
result = self.sweeper.read()
sweeper.finish()  
```

**Comment by ClaGause** [comment]
And can I access the webserver with using python (`impedance.set('path', '/settings/LabOne/WebServer')`)?

**Comment by ClaGause** [comment]
> Thank you! I changed it accordingly but it still doesn't seem to work. I'm specifing the path with sweeper.set('save/directory', 'path') when setting the filename, could that somehow be problematic? Or maybe it's the placement? I've placed it like this:
> 
> ```
> sweeper.set('save/directory', 'path') 
> sweeper.set('save/filename', measurement['saveas_var'])
> sweeper.set('save/fileformat', measurement['fileformat_var'])
> start_time = time.time()
> sweeper.execute()
> sweeper.set('endless', 1)
> while (time.time() - self.start_time) < (measurement['duration_var'] * measurement['durationunit_var']):
>          time.sleep(0.05)
> sweeper.set('endless', 0)
> sweeper.set('save/save', 1)
> result = self.sweeper.read()
> sweeper.finish()  
> ```

Now it worked, thank you for your help! The second question still stands though.

**Comment by ClaGause** [comment]
Now it worked, thank you for your help!

**Comment by mehdialem** [comment]
> And can I access the webserver with using python (`impedance.set('path', '/settings/LabOne/WebServer')`)?

The LabOne APIs including the Python API run on the host computer and cannot have access to the files in MFLI/MFIA storage managed by the Webserver running on the device. So if the compensation files are saved on the MFLI/MFIA, the Python API can't understand the "path" to the device, and you need to download the compensation files and put them in a local folder in your computer and inform the impedance module by assigning the path to the local folder. 

If the files are in your computer, then, you can assign the full path to the impedance module, for example if the files in the default Webserver setting directory in your computer: 

`impedance.set('path', 'C:\Users\[user]\AppData\Roaming\Zurich Instruments\LabOne\WebServer\setting')`

**Comment by ClaGause** [comment]
One more question, is there a way to save the data as a .txt file, like when using the web-based application with only three columns (frequency, Impedance, Phase)?

**Comment by mehdialem** [comment]
> One more question, is there a way to save the data as a .txt file, like when using the web-based application with only three columns (frequency, Impedance, Phase)?

The API always records the full data set. This can be in text-based format like `.csv` or tailored for numeric tools like `.mat` and `.h5`. Then, the user can extract the desired data from the full data set and process it similar to what the GUI does using basic post-processing. 

In the case of Sweeper module for impedance, there is also `.txt` format which is tailored for ZView program. This has a smaller data set with focus on relevant impedance data.
